eyWebManagementPortal/accounts/urls.py
from django.conf.urls import url
from django.urls import path
from .views import (
    login_view,
    logout_view,
    change_password,
    register_view,
    list_users_view,
)

urlpatterns = [
    url(r"^login/$", login_view, name = "login"),
    url(r"^logout/$", logout_view, name="logout"),
    url(r"^register/$", register_view, name="register"),
    url(r"^list_users/$", list_users_view, name="list_users"),
    url(r"^change_password/$", change_password, name="change_password"),
]

eyWebManagementPortal/eyWebManagementPortal/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from backupDatabase.views import (
    home,
    db_backup,
    ajax_load_db_instances,
    ajax_load_applications,
    ajax_load_databases
)


urlpatterns = [
    # ... other urls
    path('', home, name="home"),
    url(r'^accounts/', include("accounts.urls")),
    path('post/ajax/applications', db_backup, name="db_backup"),
    path('SuggestApplication/', ajax_load_applications, name='ajax_load_applications'),
    path('SuggestDbInstances/', ajax_load_db_instances, name='ajax_load_db_instances'),
    path('SuggestDatabases/', ajax_load_databases, name='ajax_load_databases'),

    # path('accounts/', include('django.contrib.auth.urls')),
    # path('login/', user_login, name='login'),
    # path('logout/', user_logout, name='logout'),
    # path('change_password/', change_password, name='change_password'),
    path('admin/', admin.site.urls),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

eyWebManagementPortal/backupDatabase/models.py
from django.db import models
from django import forms
# Create your models here.


class DbBackupModel(models.Model):
    select_application = models.CharField(max_length=100)
    select_db_instance = models.CharField(max_length=100)
    select_database = models.CharField(max_length=100)
    db_backup_type = models.CharField(max_length=100)

    # def __str__(self):
    #     return self.select_application, self.select_db_instance, self.select_database

eyWebManagementPortal/backupDatabase/forms.py
from .models import DbBackupModel
from django import forms
import json


class DbBackupForm(forms.ModelForm):
    default_choice = [('', '----------')]
    db_backup_type_choices = [('', '----------'), 
                                ('Full', 'Full'), 
                                ('Inc', 'Diff'), 
                                ('T-Log', 'T-Log')]
    select_db_instance = forms.ChoiceField(choices=default_choice)
    select_database = forms.ChoiceField(choices=default_choice)
    db_backup_type = forms.ChoiceField(choices=db_backup_type_choices)

    def __init__(self, *args, **kwargs):
        super(DbBackupForm, self).__init__(*args, **kwargs)
        ## add a "form-control" class to each form input
        ## for enabling bootstrap

        for name in self.fields.keys():
            self.fields[name].widget.attrs.update({
                'class': 'form-control',
            })

    class Meta:
        model = DbBackupModel
        fields = ("__all__")

eyWebManagementPortal/templates/base.html
<!DOCTYPE html>
<html lang="en">

{% load static %}

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{% block title %}{% endblock title %}</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" type="text/css">
    {% block style %}
    {% endblock style %}
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-dark fixed-top" style="background-color: #563d7c;">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
            <a class="navbar-brand" href="/">EY Portal</a>
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="/">DB Backup <span class="sr-only">(current)</span></a>
                </li>
                {% comment %} <li class="nav-item">
                    <a class="nav-link" href="{% url 'register' %}">Register NewUser</a>
                </li> {% endcomment %}
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown1" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    User Actions
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown1">
                    <a class="dropdown-item" href="{% url 'register' %}">Register NewUser</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="{% url 'list_users' %}">List Users</a>
                    </div>
                </li>
            </ul>
            <ul class="navbar-nav pull-right">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown2" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    {% if user.is_authenticated %}
                        Welcome, {{ user.username }}!
                    {% endif %}
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown2">
                        <a class="dropdown-item" href="{% url 'change_password' %}">Change Password</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="{% url 'logout' %}">LogOut</a>
                    </div>
                </li>
            </ul>
        </div>
    </nav>
    </br></br></br>

    {% block content %}
    {% endblock content %}

    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>

    {% block javascript %}
    {% endblock javascript %}
</body>

</html>

eyWebManagementPortal/templates/index.html
{% extends "base.html" %}

{% load static %}

{% block content %}
<div class="container-fluid">
    <form id="db-backup-form">
        <div class="row">
            {% csrf_token %}
            {% for field in form %}
            <div class="form-group col-4">
                <label class="col-12">{{ field.label }}</label>
                {{ field }}
            </div>
            {% endfor %}
            <input type="submit" class="btn btn-primary mx-auto" value="Backup DB" />
        </div>
    <form>
</div>
<hr />

<div class="container-fluid">
    <table class="table table-striped table-sm" id="db_backup_table_display">
        <thead>
            <tr>
                <th>Application</th>
                <th>DB Instance</th>
                <th>Database</th>
            </tr>
        </thead>
        <tbody>
        {% for db_data in db_backup_data %}
        <tr>
            <td>{{db_data.select_application}}</td>
            <td>{{db_data.select_db_instance}}</td>
            <td>{{db_data.select_database}}</td>
        </tr>
        {% endfor %}
        </tbody>
    </table>

</div>
{% endblock content %}

{% block style %}
<link rel="stylesheet" href="{% static 'css/jquery-ui.css' %}" type="text/css">
{% endblock style %}

{% block javascript %}
<script src="{% static 'js/jquery-ui.js' %}"></script>
<style>
    .ui-autocomplete {
        max-height: 200px;
        overflow-y: auto;
        /* prevent horizontal scrollbar */
        overflow-x: hidden;
        /* add padding to account for vertical scrollbar */
        padding-right: 20px;
    } 
</style>
<script>
    $(document).ready(function(){
        $('#id_select_application').on("blur", function(e){
            // preventing from page reload and default actions
            e.preventDefault();
            var app_name = $("#id_select_application").val();
            $.ajax({
                url:            "{% url 'ajax_load_db_instances' %}",
                data:           {'appName': app_name},
                type:           'GET',
                success: function(data)
                {   
                    // $('select[name=select_db_instance]').html("");
                    // $('select[name=select_db_instance]').append($('<option></option>').html("---------"));
                    $.each(data, function(index, text)
                    {

                        $('select[name=select_db_instance]').append(
                            $("<option></option>").val(text).html(text)
                        );
                    })
                }
            });
        });
    });
</script>
<script>
    $(document).ready(function(){
        $('#id_select_db_instance').on("change", function(e){
            // preventing from page reload and default actions
            e.preventDefault();
            var db_instance_name = $("#id_select_db_instance").children("option:selected").text();
            $.ajax({
                url:            "{% url 'ajax_load_databases' %}",
                data:           {'db_instance_name': db_instance_name},
                type:           'GET',
                success: function(data)
                {   
                    $.each(data, function(index, text)
                    {
                        $('select[name=select_database]').append(
                            $("<option></option>").val(text).html(text)
                        );
                    })
                }
            });
        });
    });
</script>
<script type="text/javascript">
    $(function() {
        $("#id_select_application").autocomplete({
            source: "{% url 'ajax_load_applications' %}",
            minLength: 2,
        });
    });
</script>
<script>
    /*
        On submiting the form, send the POST ajax
        request to server and after successfull submission
        display the object.
    */
    $("#db-backup-form").submit(function (e) {
        // preventing from page reload and default actions
        e.preventDefault();
        // serialize the data for sending the form data.
        // var serializedData = new FormData($('form').get(0));
        // debugger;

        // using jQuery
        function getCookie(name) {
            var cookieValue = null;
            if (document.cookie && document.cookie !== '') {
                var cookies = document.cookie.split(';');
                for (var i = 0; i < cookies.length; i++) {
                    var cookie = jQuery.trim(cookies[i]);
                    // Does this cookie string begin with the name we want?
                    if (cookie.substring(0, name.length + 1) === (name + '=')) {
                        cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                        break;
                    }
                }
            }
            return cookieValue;
        }
        //var token = getCookie('csrftoken');

        var serializedData = $(this).serialize();
        // var token = $("#db-backup-form").find('input[name=csrfmiddlewaretoken]').val()
        // var select_application = $("#id_select_application").val();
        // var select_db_instance = $("#id_select_db_instance option:selected").text();
        // var select_database = $("#id_select_database option:selected").text();
        // make POST ajax call
        // var serializedData = {'select_application': select_application, 'select_db_instance': select_db_instance, 'select_database': select_database, 'csrfmiddlewaretoken': token}
        
        $.ajax({
            type: 'POST',
            url: "{% url 'db_backup' %}",
            data: serializedData,
            success: function (response) {
                // on successfull creating object
                // 1. clear the form.
                $("#db-backup-form").trigger('reset');
                // 2. focus to nickname input 
                $("#id_select_application").focus();

                // display the newly friend to table.
                var instance = JSON.parse(response["instance"]);
                var fields = instance[0]["fields"];
                $("#db_backup_table_display tbody").prepend(
                    `<tr>
                    <td>${fields["select_application"]||""}</td>
                    <td>${fields["select_db_instance"]||""}</td>
                    <td>${fields["select_database"]||""}</td>
                    </tr>`
                )
            },
            error: function (response) {
                // alert the error if any error occured
                alert(response["responseJSON"]["error"]);
            }
        })
    })
</script>
{% endblock javascript %}

eyWebManagementPortal/templates/login_remove.html
<!DOCTYPE html>
{% load static %}

<html lang="en-us" >
<head>
  <title>Log in | EY WEB Management Portal</title>
  <link rel="stylesheet" type="text/css" href="{% static "/admin/css/login.css" %}">
  <link rel="stylesheet" type="text/css" href="{% static "/admin/css/base.css" %}">
  <meta name="viewport" content="user-scalable=no, width=device-width, initial-scale=1.0, maximum-scale=1.0">
  <link rel="stylesheet" type="text/css" href="{% static "/admin/css/responsive.css" %}">
  <meta name="robots" content="NONE,NOARCHIVE">
</head>

<body class=" login" data-admin-utc-offset="0">
<h2 class="form-signin-heading">{{ message }}</h2>
  <!-- Container -->
  <div id="container">
    <!-- Header -->
    <div id="header">
      <div id="branding">
        <h1 id="site-name"><a href="/login/">EY WEB Management Portal</a></h1>
      </div>  
    </div>
    <!-- END Header -->

    <!-- Content -->
    <div id="content" class="colM">
      <div id="content-main">
        <form method="post">
          {% csrf_token %}
          <div class="form-row">
            <label class="required" for="id_username">Username:</label> 
            <input type="text" name="username" autofocus autocapitalize="none" autocomplete="username" maxlength="150" required id="id_username">
          </div>
          
          <div class="form-row">
            <label class="required" for="id_password">Password:</label> 
            <input type="password" name="password" autocomplete="current-password" required id="id_password">
          </div>

          <div class="form-row">
            <label>
              <input type="checkbox" value="remember-me"> Remember me
            </label>
          </div>

          <div class="submit-row">
            <label>&nbsp;</label><input type="submit" value="Log in">
          </div>
        </form>
      </div>  
      <br class="clear">
    </div>
    <!-- END Content -->
    <div id="footer"></div>
  </div>
<!-- END Container -->
</body>
</html>